function createfigure(XData1, YData1, XData2, YData2, YData3)
%CREATEFIGURE(XData1, YData1, XData2, YData2, YData3)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  YDATA3:  line ydata

%  Auto-generated by MATLAB on 06-Feb-2020 18:25:44

% Create figure
figure('WindowState','maximized',...
    'Name','Linear Analysis Tool Plot: Nyquist Plot 2',...
    'OuterPosition',[-6.33333333333333 743.666666666667 1934.66666666667 1064.66666666667]);

% Create ylabel
ylabel('Imaginary Axis','Units','normalized','HorizontalAlignment','center',...
    'Visible','on');

% Create xlabel
xlabel('Real Axis','Units','normalized','HorizontalAlignment','center',...
    'Visible','on');

% Create title
title('Nyquist Diagram','Units','normalized','HorizontalAlignment','center',...
    'FontWeight','bold',...
    'Interpreter','none');

% Create axes
axes1 = axes('Position',...
    [0.142702893436838 0.11 0.762297106563162 0.77531746031746]);

% Create line
line(XData1,YData1,'Visible','off');

% Create hggroup
hggroup('DisplayName','linsys1','Tag','');

% Create line
line(XData2,YData2,'Color',[0 0.447 0.741]);

% Create line
line(XData2,YData3,'Color',[0 0.447 0.741]);

% Create title
title('From: Gain3  To: Gain5','Units','normalized','Interpreter','none',...
    'Color',[0.4 0.4 0.4]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-600 800]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1500 1500]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XColor',[0.4 0.4 0.4],'YColor',[0.4 0.4 0.4]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.823679661158159 0.834685860095137 0.0460069444444444 0.0197817189631648]);

